<?php
  $page = 'index';
  include('inc/top.inc.php') 
?>

<p><?= l("La Cocina presents a one-day street food feeding frenzy!  We&#x27;re closing the street. We&#x27;re pouring street food inspired cocktails. We&#x27;re serving casual, affordable food from every corner of the globe. Come eat with us. This is food for all. Admission is free and open to the public. Food and drinks will be sold by each vendor, with nothing costing more than $8.", "&iexcl;La Cocina presenta un d&iacute;a de celebraci&oacute;n de comida callejera! Cerraremos la calle. Serviremos cocteles inspirados por la comida callejera. Habr&aacute; comida informal, a buen precio, de todas las esquinas del mundo. Venga a comer con nosotros, ser&aacute; comida para todos. La entrada es gratis y el evento abierto al p&uacute;blico. La comida y bebida ser&aacute; vendida por cada vendedor, nada costar&aacute; m&aacute;s de $8") ?> <a href="http://www.brownpapertickets.com/event/72618"><?= l("Buy a passport", "Puede comprar un pasaporte") ?></a> <?=l("for savings and the freedom not to hassle with an ATM.", "para ahorrar un poco y para no tener que lidiar con tener efectivo.") ?></p>

<p><?= l("The day-long block party will bring together micro-entrepreneurs, informal food vendors and renowned chefs to celebrate great street food, entrepreneurial spirit and the vibrant communities of San Francisco. In addition to delicious eats, the festival will feature a beer and spirits garden, roving street musicians, street art projects, and a hands-on children&#x27;s play area, as well as multi-lingual services for attendees. The event is a benefit for La Cocina.", "El festival durar&aacute; todo el d&iacute;a y juntar&aacute; a micro-empresarios, vendedores informales, y chefs renombrados para celebrar la comida callejera, el esp&iacute;ritu del empresario y las diversas comunidades de San Francisco. Adem&aacute;s de la comida, el festival tendr&aacute; una zona de cerveza, vino y licores, m&uacute;sicos m&oacute;viles, proyectos de arte callejero, una zona de actividades para los ni&ntilde;os, y informaci&oacute;n en ingles y en espa&ntilde;ol para los que vayan. Este evento beneficia La Cocina. ") ?></p>

<p><?= l("The San Francisco Street Food Festival is a collaborative project with a special focus on the transition from informal to formal food businesses. Through partnerships with both non-profits and highly regarded restaurants, this event will work to connect communities throughout San Francisco&#x27;s spectrum of class and culture to the everyday food that we all eat and love. The festival is a sister event to the Eat Real Festival, which will be taking place in Oakland&#x27;s Jack London Square August 28 through the 30, 2009.", "El festival durar&aacute; todo el d&iacute;a y juntar&aacute; a micro-empresarios, vendedores informales, y chefs renombrados para celebrar la comida callejera, el esp&iacute;ritu del empresario y las diversas comunidades de San Francisco. Adem&aacute;s de la comida, el festival tendr&aacute; una zona de cerveza, vino y licores, m&uacute;sicos m&oacute;viles, proyectos de arte callejero, una zona de actividades para los ni&ntilde;os, y informaci&oacute;n en ingles y en espa&ntilde;ol para los que vayan. Este evento beneficia La Cocina. ") ?></p>


<?php include('inc/bottom.inc.php') ?>