<?php
  $page = 'index';
  include('inc/top.inc.php') 
?>

<h1>Dear Street Food Lovers,</h1>


<p>First of all, thank you. Thank you. Thank you. Thank you. When we began planning this event over a year ago, it was a small conversation between a couple of friends. It was a different city then&ndash;street food still meant illegal elotes, churros, tamales and bacon-wrapped hot dogs; nobody was on twitter. The vendors were our clients (<a href="http://www.lacocinasf.org/">www.lacocinasf.org</a>) and people like them. Our idea was simple&ndash;to put together a break-even event with a focus on the people who make their living taking the food they love to the streets, and to talk about the hoops they have to jump through to make that possible.</p>
 
<p>We envisioned a smallish block party, with a couple of special guests (the restaurants) to show that no matter what level of the food world you live in, we all like to make and eat the food we find on the street. As the event grew, and street food became more popular, we looked at every dimension and tried to make the event as inclusive as possible. This festival was put together on a shoestring, and then built on the backs of people who believe in vendors like ours. From that perspective, Saturday was a testament to the power of food to bring people together. And what was Saturday?</p>

<ul>
  <li>5 informal (normally selling illegally) vendors who formalized for the first time, secured all paperwork and brought their product to the masses (you)</li>
  <li>9 La Cocina vendors, most of whom began selling on the streets and in their homes, scaled up, made it happen and made what they love into a viable business</li>
  <li>8 restaurants, all local and small businesses (not to mention supporters of local business in all its forms) decided to play by our rules, rough tough cooking conditions and price their food between $3 and $8</li>
  <li>An unimaginable amount of you all came out and supported what is most essential about street food: that it brings people together, that it is food worth caring about and that it can be amazing no matter who sells it, who eats it or what it costs.   </li>
</ul>

<p>From the minute we opened the gates to Folsom Street, we could not believe how wonderful the people in this city are. People from all over were excited to eat the foods that the people we love make, and that&#x27;s a beautiful thing to <a href="http://www.flickr.com/photos/hawktane/3850147422/in/set-72157622122666856/">see</a>. From there, we simply tried to do what we could to make sure the food kept flowing. In looking back at the event, we know that there are plenty of things that can (and will) be improved, and we&#x27;d love to keep hearing your opinions. But we also want to make sure to mention the wonderful things that you all made happen at this event. From the great folks at <a href="http://www.thegogame.com/">The Go Game</a> and their excited gamers, to the street food vendors who had never sold more than $500 in product before, there was so much to be proud of. La Cocina thanks you.</p>
<p>Your presence and support for this event meant the very first legal sales for businesses like the bacon-wrapped hot dog vendor, the cut-fruit vendor from the Mission, Creme Brulee Cart, Wholesome Bakery, Endless Summer Sweets and more. Vendors who began selling from their homes and from the streets now had the opportunity to sell to thousands of people like you, and that&#x27;s a beautiful thing. <a href="http://blogs.sfweekly.com/foodie/2009/08/vendor_busted_at_saturdays_str.php">Formalizing a business is hard</a>, and we&#x27;re proud that you all believe that we should all work together to change what&#x27;s possible in this city. To that extent, please check out Street Food Declaration on this page. </p>
<p>In the meantime, a final and huge thank you to everyone who came out to support the event! We are so overwhelmed by your interest and desire to support your local community that simply writing this seems insufficient. We know the lines were long and that it was crowded, but we believe that to be both a testament to you, the customer, and also the need for this city to have a real conversation about street food. Also, we believe that it is inspiration enough to keep creating events that focus those energies on the positive community building that you&#x27;ve started.</p>
<p>Thank you for your kindness and support, your patience and your good spirit and, most importantly, for your belief that food is important enough to be celebrated. We will work tirelessly to continue to support entrepreneurs who do what they love in order to make a living, and to connect them to the people who love them for doing that. </p>
<p>Thank you. Thank you. Thank you. </p>
<p>Sincerely,<br />San Francisco&#x27;s First Street Food Festival</p>


<!-- <p><?= l("La Cocina presents a one-day street food feeding frenzy!  We&#x27;re closing the street. We&#x27;re pouring street food inspired cocktails. We&#x27;re serving casual, affordable food from every corner of the globe. Come eat with us. This is food for all. Admission is free and open to the public. Food and drinks will be sold by each vendor, with nothing costing more than $8.", "&iexcl;La Cocina presenta un d&iacute;a de celebraci&oacute;n de comida callejera! Cerraremos la calle. Serviremos cocteles inspirados por la comida callejera. Habr&aacute; comida informal, a buen precio, de todas las esquinas del mundo. Venga a comer con nosotros, ser&aacute; comida para todos. La entrada es gratis y el evento abierto al p&uacute;blico. La comida y bebida ser&aacute; vendida por cada vendedor, nada costar&aacute; m&aacute;s de $8") ?> <a href="http://www.brownpapertickets.com/event/72618"><?= l("Buy a passport", "Puede comprar un pasaporte") ?></a> <?=l("for savings and the freedom not to hassle with an ATM.", "para ahorrar un poco y para no tener que lidiar con tener efectivo.") ?></p>

<p><?= l("The day-long block party will bring together micro-entrepreneurs, informal food vendors and renowned chefs to celebrate great street food, entrepreneurial spirit and the vibrant communities of San Francisco. In addition to delicious eats, the festival will feature a beer and spirits garden, roving street musicians, street art projects, and a hands-on children&#x27;s play area, as well as multi-lingual services for attendees. The event is a benefit for La Cocina.", "El festival durar&aacute; todo el d&iacute;a y juntar&aacute; a micro-empresarios, vendedores informales, y chefs renombrados para celebrar la comida callejera, el esp&iacute;ritu del empresario y las diversas comunidades de San Francisco. Adem&aacute;s de la comida, el festival tendr&aacute; una zona de cerveza, vino y licores, m&uacute;sicos m&oacute;viles, proyectos de arte callejero, una zona de actividades para los ni&ntilde;os, y informaci&oacute;n en ingles y en espa&ntilde;ol para los que vayan. Este evento beneficia La Cocina. ") ?></p>

<p><?= l("The San Francisco Street Food Festival is a collaborative project with a special focus on the transition from informal to formal food businesses. Through partnerships with both non-profits and highly regarded restaurants, this event will work to connect communities throughout San Francisco&#x27;s spectrum of class and culture to the everyday food that we all eat and love. The festival is a sister event to the Eat Real Festival, which will be taking place in Oakland&#x27;s Jack London Square August 28 through the 30, 2009.", "El festival durar&aacute; todo el d&iacute;a y juntar&aacute; a micro-empresarios, vendedores informales, y chefs renombrados para celebrar la comida callejera, el esp&iacute;ritu del empresario y las diversas comunidades de San Francisco. Adem&aacute;s de la comida, el festival tendr&aacute; una zona de cerveza, vino y licores, m&uacute;sicos m&oacute;viles, proyectos de arte callejero, una zona de actividades para los ni&ntilde;os, y informaci&oacute;n en ingles y en espa&ntilde;ol para los que vayan. Este evento beneficia La Cocina. ") ?></p>

<p><?= l('<a target="_blank" href="SFSF_map.pdf">Click here to download a map of the festival</a><p></p>  <img align="left" style="width: 100px; height: auto; margin-right: 5px;" src="/img/logo_sfbc.gif" alt="SFBC" /> The SF Bike Coalition will be providing the bike valet', '') ?></p> -->


<?php include('inc/bottom.inc.php') ?>