<?php
  $page = 'street_food_policy';
  include('inc/top.inc.php') 
?>

<p><?= l('Street food is both everywhere and nowhere in San Francisco. You can wander between taco trucks, food carts, pop-up vendors and weekly farmers markets but still not get a real sense of the streets. And while each of these groups have existed in the city for a very long time, recent social networking websites have given once underground vendors a way to promote themselves and connect with their customers in <a href="http://www.nytimes.com/2009/07/23/business/smallbusiness/23twitter.html?_r=3&scp=1&sq=twitter%20street%20food&st=cse" target="_blank"> new and unique ways</a>. The result is that while street food is experiencing a huge rise in popularity, it\'s still very much an informal economy that is struggling to maintain its vibrancy and diversity while coping with city laws and ordinances that have (often) been established to favor the existing tax base of brick and mortar businesses. The simple fact is that while <a href="http://www.sfgate.com/cgi-bin/article.cgi?type=food&f=/c/a/2009/05/26/MN6317MLGI.DTL" target="_blank">many people start mobile food carts</a> because it is an inexpensive option for culinary entrepreneurs, the goal of transitioning to fully legal members of the San Francisco business community is expensive and full of barriers for many vendors.',
'La comida callejera esta en todas partes y en ning&uacute;n lado de San Francisco. Puede uno caminar entre camiones loncheras vendiendo tacos, paleteros, y en los mercados pero no tendr&aacute; una verdadera imagen de las calles. Y mientras estos grupos de vendedores han existido mucho tiempo, recientemente, nuevas tecnolog&iacuteas de redes sociales han dado a los vendedores que antes viv&iacutean bajo el radar una manera nueva de promoverse y conectarse con sus clientes. El resultado es que mientras la comida callejera se est&aacute; volviendo m&aacute;s popular, sigue siendo una econom&iacutea informal. Es dif&iacutecil que los vendedores mantengan su diversidad y energ&iacutea al lidiar con las leyes de la ciudad y los reglamentos que han (normalmente) sido establecidos para beneficiar a los negocios que tienen espacio permanente. Mucha gente empieza a vender comida en manera m&oacute;vil porque es una opci&oacute;n barata pero la meta de cambiar a tener una operaci&oacute;n legal y ser parte de la comunidad de negocios de San Francisco es caro y hay muchas razones por las que no se puede lograr.') ?></p>


<h3><?= l('10 Things you may not know about San Francisco street food:','10 Cosas que Puede Ser que No Sepa de la Comida Callejera de San Francisco') ?></p></h3>

<p><?= l('
<ol>
  <li>If a food truck in San Francisco is on public property (a street) it must have a permit, which can cost in excess of $10,000 per year.</li>
  <li>Food trucks themselves can cost between $60-$150,000 due to requirements from city and state health, fire, and police departments; these fees often eliminate the cost benefits of "starting small" with a mobile catering business.</li>
  <li>Catering trucks can\'t operate within 1500 feet of a public school.</li>
  <li>Food trucks are not allowed a permitted legal stop within 300 Feet (or 2 Blocks) of another legal stop. Therefore legal congregating of a variety of vendors is impossible.</li>
  <li>A permitted stop is not allowed within 300 feet (or 2 blocks) of an existing brick and mortar business that sells a similar type of product. Brick and mortar vendors are able to appeal to (and have mobile stops revoked by) their district police departments if they feel their business is being adversely affected by the mobile vendors.</li>
  <li>All new (or newly purchased) carts or trucks must have a three part hand washing sink and an enclosed cooking area and ventilation (trucks must also have a separate hand washing sink). These requirements are impossible in food carts because San Francisco limits the size of food carts within the city to 3ft x 4ft x 5ft high. Therefore, cooking fresh food from a cart is legally impossible in San Francisco.</li>
  <li>All new (or newly purchased) trucks must have refrigerated coolers, an expensive Department of Health upgrade that increases the cost of a vehicle significantly. </li>
  <li>San Francisco limits the number of mobile permits that one person can own to one per family.</li>
  <li>The San Francisco Police Department has no specific "shut down time" for mobile carts, although they have been resistant to issue mobile truck permit stops past early evening. </li>
  <li>Trucks and Carts serving food on private property are governed by the Health Department and City Planning (Zoning Board). The processing time for these locations has recently increased to 90 Days. In addition, the San Francisco Health Department requires a Mobile vendor to have an accessible bathroom within 300 feet of their operation for the use of employees.</li>
</ol>', 
'<ol><li>Si un cami&oacute;n de comida esta en propiedad p&uacute;blica de San Francisco (como una calle) tiene que tener un permiso que puede costar hasta m&aacute;s de $10,000 al a&ntilde;o.</li>
	<li>Los camiones de comida pueden costar entre $60-$150,000 por los requerimientos de la ciudad y del estado de los departamentos de salubridad, fuego, y polic&iacutea. Estos gastos pueden eliminar los beneficios y ahorros de "empezar peque&ntilde;o" con vender comida m&oacute;vil como negocio. </li>
	<li>Los camiones de comida no pueden operar en 1500 pies de una escuela p&uacute;blica.
	<li>Los camiones de comida no pueden parar legalmente en 300 pies (o 2 cuadras) de otra parada legal. Eso significa que tener un grupo de vendedores es legalmente imposible.</li>
	<li>No se permiten paradas en 300 pies (o 2 cuadras) de un negocio permanente que vende productos similares. Los vendedores permanentes pueden pelear (y tener los permisos de paradas m&oacute;viles quitadas) por el departamento de polic&iacutea de su distrito si piensan que su negocio est&aacute; siendo afectado adversamente por tener vendedores m&oacute;viles cerca.</li>
	<li>Todos los camiones o carritos nuevos (o nuevamente comprados) tienen que tener un fregadero de 3 compartimentos y una zona cerrada para cocinar y ventilaci&oacute;n (los camiones tienen que tener tambi&eacute;n un lavabo de manos.) Estos requerimientos son imposibles en los carritos porque San Francisco limita el tama&ntilde;o de los carritos de comida dentro de la ciudad a ser de 3pies x 4pies x 5 pies de altura. Por eso es imposible cocinar comida afuera desde un carrito en San Francisco.</li>
	<li>Todos los camiones nuevos (o nuevamente comprados) tienen que tener una zona de refrigerador. Este cambio, forzado por el Departamento de la Salud, es muy costoso.</li>
	<li>San Francisco limita el n&uacute;mero de permisos m&oacute;viles que una persona puede tener a uno por familia.
	<li>El departamento de Polic&iacutea de San Francisco no tiene una hora espec&iacutefica de cerrada para vendedores de comida m&oacute;viles pero han sido resistentes a dar permisos para m&aacute;s tarde del anochecer.</li>
	<li>Los camiones y los carritos que sirven comida en propiedad privada son gobernados por el Departamento de la Salud y los que Planean la Ciudad (Zoning). Tarda 90 d&iacuteas procesar los permisos para estos locales. Adem&aacute;s, el Departamento de Salud de San Francisco requiere que un vendedor m&oacute;vil tenga un ba&ntilde;o accesible a menos de 300 pies de su operaci&oacute;n para los empleados.</li></ol>
') ?></p>




<p><?= l('These regulations, among others, make selling outdoors difficult, and make both selling food while moving and preparing food outdoors nearly impossible. Most of the vendors you see on the streets of San Francisco today - from mobile ice cream and tamale vendors to late - night hot dog grills - are all operating informally and subject to fines.', 'Estas reglas, y otras, hacen que vender afuera sea muy dif&iacutecil y hace que preparar comida mientras uno est&aacute; cambiando de lugar sea casi imposible legalmente. La mayor&iacutea de los vendedores que se ven en las calles de San Francisco - desde los helados hasta los que venden tamales y hotdogs - todos operan informalmente y pueden ser multados.') ?></p>

<h3><?= l('Places to Find Street Food in San Francisco', '') ?></h3>
<p><?= l('Street Food in San Francisco has historically been focused on Hispanic cuisine and, as a result, the Mission has been (and continues to be) the epicenter of street food in San Francisco. While tamales and bacon dogs are still plentiful around Dolores Park and up and down Mission Street, the rise of specialty food carts selling Cr&egrave;me Brul&eacute;e, Curry, Soup and BBQ speak to the diversity of flavors that are now being produced in the area.</p> 
<p>Additionally, Farmers markets, like the Alemany Market, have been a long-time source of street food in San Francisco. As the popularity of these markets increases, the number of vendors around the city has also increased and the Ferry Plaza Farmers Market has dedicated its Thursday Market specifically to street food. </p>
</p><a href="http://www.7x7.com/" target="_blank">Check out this map to find out where vendors are located.</a>',

'<p>Hist&oacute;ricamente la comida callejera en San Francisco ha sido enfocada a la comida Latina y, como resultado, la Misi&oacute;n ha sido y sigue siendo el centro de la comida callejera de San Francisco. Los tamales y los hotdogs con tocino siguen existiendo alrededor de Dolores Park y por la calle Mission, y tambi&eacuten ha subido la cantidad de vendedores de comida especial como Cr&egrave;me Brul&eacute;e, Curry, Sopa, y BBQ y eso es prueba de la diversa cantidad de sabores que ahora son producidos en la zona.</p>
 <p>Adem&aacute;s, los mercados, como el Mercado de Alemany, han sido lugares de comida callejera en San Francisco. Como ha subido su popularidad, en n&uacute;mero de vendedores tambi&eacuten ha subido y el Mercado del Ferry Plaza ha decidido dedicar el mercado del jueves a la comida callejeara.</p>
 <p>Vea <a href="http://foodcartsportland.com/">este mapa</a> para ver donde se encuentran los vendedores.</p>') ?></p>




<h3><?= l('Street Food in Other Cities', 'Lugares para Encontrar Comida Callejera en San Francisco') ?></h3>

<?= l('<p><strong>New York City</strong>\'s regulations are just as tough on street vendors as San Francisco\'s; the vibrant street food scene is mostly supported by a <a href="http://nymag.com/restaurants/features/33530/">black-market</a> in permits, street locations, etc. These <a href="http://www.nytimes.com/2009/07/01/dining/01truck.html?_r=2&amp;pagewanted=1">turf wars</a> make it harder for people to work within the system than out. The city is attempting to crack down on the black market and regulate street food more, which many fear could end up destroying the culture. The various fines imposed, such as for blocking a sidewalk or not displaying the license conspicuously, can cost up to $1000, which can be more than a week\'s worth of income.</p>

<p><strong>Seattle</strong>\'s regulations are also tough, and the city is working on expanding and &quot;streamlining&quot; the permit process to make it easier for street food vendors; Mayor Greg Nickels is spearheading this <a href="http://www.thestranger.com/seattle/taking-it-to-the-streets/Content?oid=1601396">process</a>. A few vendors have already assembled and they are planning <a href="http://seattlestreetfood.blogspot.com/">a Seattle Street Food Market</a>, to be launched later this summer.</p>

<p><strong>Portland</strong> seems to be the city with the most streamlined policies around street food. Potential street vendors need permission from the adjacent property owners of the spot they want to set up their cart, which means that they cannot rove around the city but also prevents the "turf wars" that are common in other cities. There are regulations about cart size and placement which does pose some limitation but fines cannot exceed $500 so businesses can more readily afford to "start small". As a result, the Street Food <a href="http://www.oregonlive.com/portland/index.ssf/2009/07/foodcart_pod_with_amenities_se.html">culture</a> is flourishing, with anything from soups and sandwiches to pasta to Polish cuisine available on the streets of Portland. A <a href="http://foodcartsportland.com/">blog</a> describes all the different carts around the city for people to go find.</p>

<p><strong>Los Angeles</strong> is having trouble, as well, with legalizing street food. The city tried to concentrate vendors into one neighborhood, which worked for a few people, but that limits the amount and type of vendors. It can take up to three years to be issued a license, and the yearly permit fee is almost $1000. However, in their attempts to change this, LA also hosts a weekly <a href="http://www.rantsandcraves.com/2009/05/back-to-basics-breed-street-food-fair.html">street food fair</a>.</p>

<p><a href="http://www.forbestraveler.com/food-drink/best-street-food-story.html">Several other cities</a>, including <strong>Cleveland</strong>, <strong>Toronto</strong>, <strong>Austin</strong>, and<strong> Washington D.C.</strong> have been attempting to ease street vending regulations to make it easier for such enterprises to grow legally. They are having similar problems as San Francisco, but agree that in the current economy it is necessary to make Street Food a viable option.</p>',

'<p><strong>Nueva York</strong> tiene reglamentos parecidos a los de San Francisco - la raz&oacute;n por su cultura de comida callejera es que hay un mercado negro de permisos, locales, etc. Hay peleas por locales y muchas reglas que lo hace m&aacute;s dif&iacutecil que la gente trabaje dentro del sistema que fuera. La ciudad est&aacute; tratando de ser m&aacute;s firme pero mucha gente le da miedo que eso acabe con la cultura. Las multas, como por bloquear la banqueta o no tener la licencia visible, pueden costas hasta $1000 lo cual puede ser m&aacute;s de una semana de ingresos.</p>

<p><strong>Seattle</strong> tambi&eacute;n tiene reglas dif&iacuteciles y la ciudad est&aacute; tratando de expandir y facilitar el proceso de sacar permisos para hacerlo m&aacute;s f&aacute;cil para los vendedores. El Alcalde, Greg Nickels, tiene liderazgo de este proyecto. Algunos vendedores ya se han juntado y est&aacute;n planeando un mercado de comida callejera para el final del verano.</p>

<p><strong>Portland</strong> parece ser la ciudad con las reglas m&aacute;s f&aacute;ciles alrededor de comida callejera. Los vendedores necesitan permiso de los due&ntilde;os de los negocios a su alrededor. Esto no permite que se est&eacute;n moviendo pero ayuda a que no hayan las peleas por lugares que son comunes en otras ciudades. Hay reglas de los tama&ntilde;os y lugares para los carritos que si tiene sus limitaciones pero las multas no pueden ser m&aacute;s de $500 entonces los negocios pueden empezar con poco. Como resultado, la cultura de comida callejera de Portland est&aacute; creciendo y hay todo desde sopas, s&aacute;ndwiches, pasta, y hasta comida polaca en las calles de la ciudad. Tambi&eacute;n hay un sitio de internet que los sigue.</p>

<p><strong>Los &Aacute;ngeles</strong> tambi&eacute;n est&aacute; teniendo problemas con legalizar la comida callejera. La  ciudad trat&oacute; de concentrar los vendedores en un vecindario. Esto funcion&oacute; para algunas gentes pero limit&oacute; mucho la cantidad y el tipo de vendedores. Puede tardar hasta tres a&ntilde;os sacar licencia y el permiso cuesta $1000 al a&ntilde;o. Est&aacute;n tratando de cambiar todo esto y han empezado un mercado de comida callejera cada semana. </p>

<p>Algunas otras ciudades incluyendo Cleveland, Toronto, Austin y Washington D.C. est&aacute;n tratando de mejorar las reglas alrededor de la comida callejera para que sea m&aacute;s f&aacute;cil que este tipo de empresa crezca legalmente. Han tenido problemas similares a San Francisco, pero saben que en esta econom&iacutea es importante que la comida callejera sea una opci&oacute;n viable.</p>') ?>


<h3><?= l('Sign our Street Food Declaration', 'Firma nuestra Declaraci&oacute;n de Comida Callejera') ?></h3>

<?= l('<p>We the undersigned believe that creating policies that support the formalization of mobile food vending in San Francisco are necessary to create a viable economic model for entrepreneurs who own small food businesses. Policies as they exist today are discouraging and create barriers rather than opportunities for the creation of viable businesses and jobs for San Franciscans. We believe that street food has the power to bring communities casual, affordable, delicious foods made by food entrepreneurs who reflect San Francisco\'s diverse population. Policies that support the formalization of mobile vending will work to connect communities throughout San Francisco\'s spectrum of class and culture to the everyday food that we all eat and love. </p>
<p>Please sign the SF Street Food Declaration below: *Your email will only be used by La Cocina to keep you informed and will not be given to any outside parties.</p>', 
'Nosotros, aqu&iacute firmando, creemos que hacer reglas que apoyan la formalizaci&oacute;n de venta de comida m&oacute;vil en San Francisco es necesario para crear un modelo econ&oacute;mico viable para empresarios que son due&ntilde;os de peque&ntilde;os negocios de comida. Las reglas, como existen hoy d&iacutea, bajan &aacute;nimos y crean barreras en lugar de oportunidades para crear negocios viables y trabajos para los de San Francisco. Creemos que la comida callejera tiene el poder de traerle a comunidades comida casual, accesible, y deliciosa hecha por empresarios que reflejan la poblaci&oacute;n diversa de San Francisco. Las reglas que apoyan la formalizaci&oacute;n de vendedores m&oacute;viles ayudar&aacute;n para conectar comunidades de todas las clases y culturas de San Francisco a la comida cuotidiana que todos comemos y amamos. ') ?>


<iframe src="http://spreadsheets.google.com/embeddedform?key=tCHyfwaV3UPRcRJ3YR3JBIg" style="padding: 10px; background-color: #fff;" width="500" height="606" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe></p>

<?php include('inc/bottom.inc.php') ?>