<?php
  $page_id = 'smart_car';
  $page_title = 'Win a smart car';
  require 'inc/top.inc.php';
?>
  <section class="kraft">
    <div class="inner">
      <h1>Can this festival get any better?</h1>
      <ul style="margin-bottom: 1em; line-height: 1.4em;">
        <li><strong>Amazing food?</strong> Check.</li>
        <li><strong>Handcrafted cocktails?</strong> Check.</li>
        <li><strong>Supporting local entrepreneurs?</strong> Check.</li>
        <li><strong>Walking away with a smart car?</strong> Amazing.</li>
      </ul>

      <p><a href="http://lacocinasf.org/">La Cocina</a> is thrilled to announce a partnership with <a href="http://www.smartcentersanfrancisco.com/">smart car center San Francisco</a>. On Saturday, August 17th, at the 5th Annual San Francisco Street Food Festival, visit the smart car tent (<a href="http://www.sfstreetfoodfest.com/downloads/2013_sfsff_map.pdf">on Folsom St between 22nd and 23rd</a>). When you take a test drive at the festival, <strong>you&rsquo;ll automatically be entered to win a Fortwo Pure Coupe model smart car.</strong></p>

      <p>Delicious food and drink and a free car? Tastes like a winning combination.</p>

      <p><a href="http://www.smartcentersanfrancisco.com/"><img src="/z_logos/sponsors/smart_car.png" alt="Smart Car San Francisco"></a></p>

      <p>Visit the smart car tent at the festival to enter!</p>

      <p><img src="images/smart_car_fortwo.jpg" alt="Fortwo Pure Coupe model smart car" width="440" height="290"/></p>

      <div class="smart_car_rules">
        <h1>Official Rules</h1>
        <h2>&ldquo;smart car Opportunity Drawing&rdquo;<br/>
          Sponsored by La Cocina, Inc.</h2>

        <ol>
          <li><strong><span class="shout">No purchase necessary to enter or win a prize. Purchase will not increase your chances of winning. Void outside of California and where prohibited or restricted by applicable law.</span></strong></li>
          <li><strong>Entry Period:</strong> The &ldquo;smart car Opportunity Drawing&rdquo; (&ldquo;<span class="legal_term">Drawing</span>&rdquo;) commences at 11 a.m. PST on August 17, 2013 and ends at 5 p.m. on August 25, 2013 (&ldquo;<span class="legal_term">Drawing Period</span>&rdquo;). All drawing tickets must be received by the end of the Drawing Period. All interpretations of these Official Rules and decisions made by La Cocina, Inc. (&ldquo;<span class="legal_term">La Cocina</span>&rdquo; or &ldquo;<span class="legal_term">Sponsor</span>&rdquo;) relating to the Drawing are final.</li>
          <li><strong>Eligibility:</strong> The Drawing is open to persons legally and physically residing in California who are at least 18 years of age at the time of entry. Employees, agents, officers, directors of La Cocina, and its partners, dealers, manufacturers, distributors, sponsors, advertising agencies, promotion and administration agencies and any entity which is involved in any aspect of the creation, production, operation, execution or fulfillment of the Drawing (&ldquo;<span class="legal_term">Drawing Entities</span>&rdquo;), and their immediate families (i.e., parents, spouse, siblings, children, grandparents, step parents, step children and step siblings, and their respective spouses, and those living in the same household, whether or not related) are not eligible to enter the Drawing. By participating in this Drawing, entrants: (a) agree to be bound by these Official Rules and by the interpretations of these Official Rules by Sponsor and by the decisions of Sponsor; (b) acknowledge compliance with these Official Rules; (c) represent and warrant that he or she meets all of the eligibility criteria set forth in these Official Rules; (d) agree to comply with any and all applicable federal, state and local laws, rules and regulations; (e) acknowledge that the Drawing is in no way sponsored, endorsed, or administered by, or associated with Facebook or Twitter; and (f) agree to release and hold harmless the Drawing Entities, Facebook and Twitter from and against any and all claims, injury or damages arising out of or relating to participation in the Drawing and/or the use, misuse or redemption of the Prize (hereinafter defined), and for any claim including claims based on defamation, publicity rights, invasion of privacy, copyright infringement, trademark infringement, or any other intellectual property related cause of action.</li>
          <li><strong>To Enter:</strong> There are two (2) methods of entry:
            <ul style="margin: 1em 0;">
              <li><strong>To Enter at the Street Food Festival:</strong> Visit the smart car booth at La Cocina&rsquo;s San Francisco Street Food Festival on August 17, 2013 and test drive a smart car to receive one (1) drawing ticket.</li>
              <li><strong>To Enter at smart center San Francisco:</strong> Visit smart center San Francisco between August 17, 2013 and August 25, 2013 and test drive a smart car to receive one (1) drawing ticket.</li>
            </ul>
            <p>Entrants may choose to make a donation to La Cocina, but no purchase is necessary. Donations are not tax deductible. Entrants may receive one (1) ticket from each method of entry for a total of two (2) entries.</p>
            <p>All information submitted by entrants is subject to and will be treated in a manner consistent with La Cocina&rsquo;s Privacy Policy accessible at sfstreetfoodfest.com. By participating in the Drawing, entrants hereby agree that La Cocina may collect and use their personal information in compliance with its Privacy Policy and acknowledge that they have read and accepted the La Cocina Privacy Policy. All information submitted by entrants is being provided to Sponsor.</p>
            <p>All entries submitted in compliance with these Official Rules and not disqualified are considered &ldquo;<span class="legal_term">Eligible Entries</span>.&rdquo;</p>
          </li>
          <li><strong>Odds:</strong> The odds of winning the Drawing depend on the total number of Eligible Entries received during the Drawing Period.</li>
          <li><strong>Prize:</strong> The Winner (hereinafter defined) will receive one (1) smart Fortwo Pure Coupe model smart car, in a color to be determined based on availability (the &ldquo;<span class="legal_term">Prize</span>&rdquo;). The total approximate retail value of the Prize is $15,909.88, which includes certain vehicle document fees, taxes and government fees.</li>
          <li><strong>Publicity Release:</strong> By participating in the Drawing, the Winner grants the right to record, film, videotape and photograph the Winner (&ldquo;<span class="legal_term">Images</span>&rdquo;) to Sponsor, and its representatives, affiliates, licensees and assigns. These Images will be owned by Sponsor. Sponsor and each of its designees shall have the right to use, re-use, reproduce, publish, display, exhibit, distribute, edit, adapt, post, stream, copy and exploit such Images, and all elements embodied therein, including any names, likenesses, address, voice, conversation, biographical and Prize information and any other attributes of Winner, individually or with others, in whole or in part, in conjunction with other material, if any, in any and all media now known or hereafter devised, for the purpose of trade, advertising, publicity, promotion, or a Drawing Winner List or any other lawful purpose whatsoever, in perpetuity, throughout the world, without additional compensation, consideration, notification or permission, except where prohibited by applicable law.</li>
          <li><strong>Winner Selection and Notification:</strong> There will be one (1) Winner selected in a random drawing from among all of the Eligible Entries (&ldquo;<span class="legal_term">Potential Winner</span>&rdquo;) on or about August 25, 2013 by Sponsor. The Potential Winner will be notified by phone or e-mail. If the Potential Winner cannot be reached by phone or e-mail and/or does not meet the eligibility requirements, the Potential Winner will be disqualified and an alternate Potential Winner will be selected in a random drawing from among all of the remaining Eligible Entries.</li>
          <li><strong>Winner Verification:</strong> To be eligible to be declared the Winner and to receive the Prize, the Potential Winner must sign and return to Sponsor, within three (3) days of issuance of such documentation from Sponsor an Affidavit of Eligibility and Release that: (a) releases Drawing Entities, Facebook and Twitter from any and all liability, loss, claims, demands, and causes of action for personal injuries or death and/or damage to personal or real property, theft, loss, or any other harm suffered directly or indirectly from Potential Winner&rsquo;s participation in the Drawing, including, but not limited to, traveling to, preparing for and/or participating in any Prize related activity, or the acceptance, possession, or use or misuse of any Prize; and (b) except where prohibited by applicable law, grants the Drawing Entities the right to use Potential Winner&rsquo;s name, picture and/or likeness, or biographical information or voice for trade, advertising and publicity purposes, in any media now known or hereafter devised, throughout the world, in perpetuity, without additional compensation or consideration or notification. Entry into the Drawing constitutes an agreement to sign such Affidavit of Eligibility and Release. If a Potential Winner does not sign such Affidavit of Eligibility and Release and return it within the time frame specified, the Potential Winner may be disqualified, at Sponsor&rsquo;s sole discretion, and the Prize forfeited. When such documentation is properly executed and providing Potential Winner is otherwise in compliance with the Official Rules, the Potential Winner will be determined to be the Drawing winner (the &ldquo;<span class="legal_term">Winner</span>&rdquo;).
            <p>Winner must also complete any additional legal documents provided by Sponsor with respect to the Prize and return them as instructed within the time frame specified or Winner may forfeit the Prize at Sponsor&rsquo;s sole discretion. If Potential Winner is unable to participate in or accept the Prize or any portion of the Prize for any reason, Sponsor will have no further obligation to the Potential Winner. Prize or Prize documents returned as undeliverable will result in forfeiture of the Prize. Sponsor expressly reserves the right to delay the announcement of the Winner for any reason Sponsor deems necessary. In addition, Sponsor reserves the right to select an alternate Winner in the event that any Potential Winner fails to comply with these Official Rules or fails to execute the documentation within the time frame specified.</p>
            <p>By participating in the Drawing, Winner acknowledges that the Drawing Entities have not and will not obtain or provide insurance of any kind relating to the Prize and that Winner will be responsible for obtaining and paying for any form of insurance relating to the Prize that Winner deems appropriate.</p>
          </li>
          <li><strong>Prize Terms:</strong> The date for fulfillment of the Prize will be on or about September 30, 2013, but is subject to change in Sponsor&rsquo;s sole discretion. If for any reason the Prize is unavailable or any Prize related event is delayed, cancelled or postponed, or for any other reason, Sponsor reserves the right to modify the Drawing in its sole discretion and award a substitute Prize, or portion of Prize, of comparable or greater value as set forth in these Official Rules. No substitution, transfer, assignment or cash equivalent of the Prize, or any portion thereof, is permitted by a Winner. Drawing Entities shall have no responsibility or obligation to a Winner who is unable or unavailable to, or who does not for any reason, accept or utilize the Prize. All costs and expenses not specifically listed above as part of the Prize are solely Winner&rsquo;s responsibility. <span class="shout">Prize is provided &ldquo;as is&rdquo; with all faults and without warranty of any kind. Entrants acknowledge that Drawing Entities have neither made nor are in any manner responsible or liable for any warranty, representation or guarantee, express or implied, in fact or in law, relative to the prize, including any express warranties provided by a prize supplier that are sent along with the prize and any implied warranty of merchantability or fitness for a particular purpose.</span> Prizes pictured in online television, print advertising, and other Drawing materials are for illustrative purposes only. Arrangements for the fulfillment of the Prize will be made by Sponsor.</li>
          <li><strong>Taxes and Fees:</strong> Winner must supply Sponsor with his or her social security number for tax purposes. An IRS Form 1099 will be issued in the name of Winner for the actual value of the Prize awarded. All federal, state and local taxes, and any other fees, costs and expenses associated with acceptance or use of the Prize not specifically provided for in these Official Rules are solely the Winner&rsquo;s responsibility.</li>
          <li><strong>General Terms:</strong> Drawing Entities, Facebook and Twitter are not responsible if the Drawing cannot take place, or if any Prize cannot be awarded due to delays, interruptions or failures due to acts of God, war, natural disasters, weather, acts or threats of terrorism, strikes, lockouts, labor disputes, work stoppages, fire, acts of government, or other events outside of the reasonable control of the Drawing Entities. If, for any reason the Drawing is not capable of running as planned, including, without limitation, infection by computer virus, bugs, tampering, unauthorized intervention, fraud, technical failures, or any other causes beyond the reasonable control of the Drawing Entities, which, in Sponsor&rsquo;s sole determination, corrupts or affects the administration, security, fairness, integrity or proper conduct of this Drawing, Sponsor reserves the right, in its sole discretion, to cancel, terminate, modify, or suspend the Drawing or any part of the Drawing. If the Drawing or any part of the Drawing is terminated or modified prior to the closing date of the Drawing, notice will be posted on sfstreetfoodfest.com if time permits and the Prize will be awarded to a Potential Winner to be selected in a random drawing from among all of the remaining uncorrupted Eligible Entries received prior to any such event outside of the reasonable control of Sponsor. Sponsor reserves the right to modify and amend these Official Rules from time to time during the Drawing for clarification purposes. Failure by Sponsor to enforce any term of these Official Rules shall not constitute a waiver of that provision.
            <p>By participating in the Drawing, all entrants agree to indemnify, defend and hold harmless the Drawing Entities, Facebook and Twitter from any and all damages, claims, and liability (including attorney&rsquo;s fees and costs) arising out of or relating in any way to entrant&rsquo;s participation in the Drawing and acceptance or use of any Prize and to release all rights to bring any claim, action or proceeding against the Drawing Entities, Facebook and Twitter. This includes, but is not limited to, any and all claims, demands and causes of action for personal injuries or death and/or damage to personal or real property, theft, loss, or damage of any kind, or any other harm suffered directly or indirectly arising from or in connection with Potential Winner&rsquo;s participation in and/or entry into the Drawing or acceptance or use of any Prize or, including, but not limited to, traveling to, preparing for and or/participating in any Drawing Prize related activity and for any claims based on publicity rights, defamation, invasion of privacy and merchandise delivery.</p>
            <p>Drawing Entities assume no responsibility for and will disqualify entries that are: stolen, late, lost, illegible, incomplete, invalid, unintelligible, altered, tampered with, unauthorized, fraudulent, damaged, destroyed, delayed, misdirected, not received, or that have incorrect or inaccurate information, whether caused by any of the equipment or programming associated with or utilized in the Drawing, or by any human, mechanical or electronic error which may occur in the processing of the entries in the Drawing, or other errors appearing within the Official Rules or in any Drawing related advertisements. Drawing Entities, Facebook and Twitter assume no responsibility for any typographical or other error in the printing of the offer, administration of the Drawing, errors in processing entries, identifying the Winner, in the announcement of the Prize and Winner, and the delivery of the Prize, any problems or technical malfunction of any telephone network or lines, mobile phone, computer systems, online systems, servers or providers, computer equipment, software, failure of any e-mail on account of technical problems or traffic congestion on the Internet or on any web site, or any combination thereof, including, without limitation, any injury or damage to entrant&rsquo;s or any other person&rsquo;s computer system/software or mobile phone or other portable electronic device related to or resulting from downloading any materials in connection with the Drawing. Sponsor reserves the right in its sole discretion to disqualify any person they suspect or find: (i) to have tampered with the entry process or the operation of the Drawing; (ii) to be acting in a disruptive manner, or with the intent to annoy, abuse, threaten or harass any other person; (iii) to display behavior that will bring such Winner or Drawing Entities into disgrace; (iv) to have provided inaccurate information on any legal documents submitted in connection with the Drawing; or (v) to be acting in violation of these Official Rules. <span class="shout">Any violation of these Official Rules by the Winner will result in such Winner&rsquo;s disqualification as the Winner of the Drawing and all privileges as the Winner will be immediately terminated.</span></p>
            <p><span class="shout">As a condition of entering the Drawing, entrant agrees that: (i) under no circumstance will entrant be permitted to obtain awards for, and entrant hereby waives all rights to claim, punitive, incidental, consequential or any other damages, other than for out-of-pocket expenses; (ii) all causes of action arising out of or connected with this drawing, or any prizae awarded, shall be resolved individually &ndash; without resort to any form of class action &ndash; by binding arbitration (by a single neutral arbitrator in accordance with the expedited rules of the America Arbitration Association; (iii) any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, but in no event shall such claims, judgments or awards include attorneys&rsquo; fees. This drawing shall be governed by and construed in accordance with the laws of the state of California exclusive of any conflict or choice of law rules; and (iv) the parties consent to exclusive personal jurisdiction in California.</p>
            <p><span class="shout">Any attempt by any person to deliberately damage or undermine the legitimate operation of the drawing may be in violation of criminal and civil law and should such an attempt be made, Sponsor reserves the right to seek remedies and damages (including attorneys&rsquo; fees) from any such person to the fullest extent permitted by applicable law.</span></p>
          </li>
          <li><strong>Request for Name of Winner and Official Rules:</strong> All requests for a copy of the Official Rules and for the name of the Winner must be made by September 30, 2013. For the name of the Winner and/or Official Rules: (i) send a self-addressed stamped envelope to: La Cocina, Inc., Attention: &ldquo;<strong>smart car Opportunity Drawing</strong>&rdquo;, 2948 Folsom St., San Francisco, CA 94110; and (ii) write, as applicable, &ldquo;Winners List&rdquo; or &ldquo;Official Rules&rdquo; on the lower left hand corner of the envelope.</li>
          <li><strong>Sponsored by:</strong> This Drawing is sponsored by La Cocina, Inc., 2948 Folsom St., San Francisco, CA 94110.
            <p><strong>This Drawing is in no way sponsored, endorsed or administered by, or associated with Facebook or Twitter.</strong></p>
          </li>
        </ol>
        <p>Copyright &copy; 2013 La Cocina, Inc. All rights reserved.</p>
      </div>
    </div>
  </section>
<?php require 'inc/bottom.inc.php'; ?>
